Repository skku-comit/comit-website-spring-server, pull requests merged in 2024-08, with the labels that each got.

#2 feat: add README.md file with temporary text
  .DS_Store
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/example/comitserver/ComitServerApplication.java
  src/main/java/com/example/comitserver/DatabaseConfig.java
  src/main/java/com/example/comitserver/controller/HelloController.java
  src/main/java/com/example/comitserver/controller/MemberController.java
  src/main/java/com/example/comitserver/domain/Member.java
  src/main/java/com/example/comitserver/dto/LoginDto.java
  src/main/java/com/example/comitserver/dto/MemberDto.java
  src/main/java/com/example/comitserver/dto/RegisterDto.java
  src/main/java/com/example/comitserver/repository/MemberRepository.java
  src/main/java/com/example/comitserver/service/MemberService.java
  src/main/java/com/example/comitserver/service/MemberServiceImpl.java
  src/main/resources/application.properties
  src/main/resources/static/home.html
  src/main/resources/templates/joinMember.html
  src/test/java/com/example/comitserver/ComitServerApplicationTests.java
Labels: feature

#6 feat: implement jwt using spring security
  build.gradle
  src/main/java/com/example/comitserver/config/CorsMvcConfig.java
  src/main/java/com/example/comitserver/config/SecurityConfig.java
  src/main/java/com/example/comitserver/controller/HelloController.java
  src/main/java/com/example/comitserver/controller/JoinController.java
  src/main/java/com/example/comitserver/controller/MemberController.java
  src/main/java/com/example/comitserver/controller/ReissueController.java
  src/main/java/com/example/comitserver/controller/UserAdminController.java
  src/main/java/com/example/comitserver/controller/UserController.java
  src/main/java/com/example/comitserver/domain/Member.java
  src/main/java/com/example/comitserver/dto/CustomUserDetails.java
  src/main/java/com/example/comitserver/dto/JoinDTO.java
  src/main/java/com/example/comitserver/dto/LoginDTO.java
  src/main/java/com/example/comitserver/dto/LoginDto.java
  src/main/java/com/example/comitserver/dto/MemberDto.java
  src/main/java/com/example/comitserver/dto/RegisterDto.java
  src/main/java/com/example/comitserver/dto/UserDTO.java
  src/main/java/com/example/comitserver/entity/RefreshEntity.java
  src/main/java/com/example/comitserver/entity/Role.java
  src/main/java/com/example/comitserver/entity/UserEntity.java
  src/main/java/com/example/comitserver/jwt/CustomLogoutFilter.java
  src/main/java/com/example/comitserver/jwt/JWTFilter.java
  src/main/java/com/example/comitserver/jwt/JWTUtil.java
  src/main/java/com/example/comitserver/jwt/LoginFilter.java
  src/main/java/com/example/comitserver/repository/MemberRepository.java
  src/main/java/com/example/comitserver/repository/RefreshRepository.java
  src/main/java/com/example/comitserver/repository/UserRepository.java
  src/main/java/com/example/comitserver/service/CustomUserDetailsService.java
  src/main/java/com/example/comitserver/service/JoinService.java
  src/main/java/com/example/comitserver/service/MemberService.java
  src/main/java/com/example/comitserver/service/MemberServiceImpl.java
  src/main/java/com/example/comitserver/service/ReissueService.java
  src/main/java/com/example/comitserver/service/UserAdminService.java
  src/main/java/com/example/comitserver/service/UserService.java
  src/main/resources/application.properties
  src/main/resources/static/home.html
  src/main/resources/templates/joinMember.html
  src/test/http/admin/users.http
  src/test/http/auth/join.http
  src/test/http/auth/login.http
  src/test/http/auth/logout.http
  src/test/http/auth/reissue.http
Labels: API, feature

#9 feat: add response DTO, add join validation
  src/main/java/com/example/comitserver/controller/JoinController.java
  src/main/java/com/example/comitserver/controller/ReissueController.java
  src/main/java/com/example/comitserver/dto/JoinDTO.java
  src/main/java/com/example/comitserver/dto/ServerErrorDTO.java
  src/main/java/com/example/comitserver/dto/ServerResponseDTO.java
  src/main/java/com/example/comitserver/exception/DuplicateResourceException.java
  src/main/java/com/example/comitserver/jwt/CustomLogoutFilter.java
  src/main/java/com/example/comitserver/jwt/LoginFilter.java
  src/main/java/com/example/comitserver/service/JoinService.java
  src/main/java/com/example/comitserver/service/ReissueService.java
  src/main/java/com/example/comitserver/uitls/ResponseUtil.java
Labels: style

#11 feat: add user create/update time
  src/main/java/com/example/comitserver/ComitServerApplication.java
  src/main/java/com/example/comitserver/DatabaseConfig.java
  src/main/java/com/example/comitserver/entity/BaseTimeEntity.java
  src/main/java/com/example/comitserver/entity/UserEntity.java
  src/main/java/com/example/comitserver/service/JoinService.java
  src/test/http/admin/users.http
  src/test/http/auth/join.http
  src/test/http/auth/login.http
  src/test/http/auth/logout.http
  src/test/http/auth/reissue.http
Labels: feature

#13 feat: add StudyAPI CRUD for client
  build.gradle
  src/main/java/com/example/comitserver/SpringConfig.java
  src/main/java/com/example/comitserver/config/SecurityConfig.java
  src/main/java/com/example/comitserver/controller/JoinController.java
  src/main/java/com/example/comitserver/controller/ReissueController.java
  src/main/java/com/example/comitserver/controller/StudyController.java
  src/main/java/com/example/comitserver/dto/StudyDTO.java
  src/main/java/com/example/comitserver/entity/StudyEntity.java
  src/main/java/com/example/comitserver/entity/enumeration/Campus.java
  src/main/java/com/example/comitserver/entity/enumeration/Day.java
  src/main/java/com/example/comitserver/entity/enumeration/Level.java
  src/main/java/com/example/comitserver/entity/enumeration/Semester.java
  src/main/java/com/example/comitserver/jwt/CustomLogoutFilter.java
  src/main/java/com/example/comitserver/jwt/LoginFilter.java
  src/main/java/com/example/comitserver/repository/StudyRepository.java
  src/main/java/com/example/comitserver/service/StudyService.java
  src/main/java/com/example/comitserver/utils/ResponseUtil.java
Labels: API, feature

#20 feat: add studyAPI CRUD for admin
  src/main/java/com/example/comitserver/controller/StudyAdminController.java
Labels: API, feature, chore

#19 fix: return UserDTO when successfully joined
  src/main/java/com/example/comitserver/controller/JoinController.java
  src/main/java/com/example/comitserver/utils/ResponseUtil.java
Labels: fix

#21 12 handle user api response/exception
  src/main/java/com/example/comitserver/config/SecurityConfig.java
  src/main/java/com/example/comitserver/controller/UserAdminController.java
  src/main/java/com/example/comitserver/controller/UserController.java
  src/main/java/com/example/comitserver/dto/UserDTO.java
  src/main/java/com/example/comitserver/exception/ResourceNotFoundException.java
  src/main/java/com/example/comitserver/jwt/JWTFilter.java
  src/main/java/com/example/comitserver/repository/UserRepository.java
  src/main/java/com/example/comitserver/service/UserAdminService.java
  src/main/java/com/example/comitserver/service/UserService.java
  src/main/java/com/example/comitserver/utils/CustomAccessDeniedHandler.java
  src/main/java/com/example/comitserver/utils/GlobalExceptionHandler.java
  src/main/java/com/example/comitserver/utils/ResponseUtil.java
Labels: feature

#29 fix: fix study api error
  src/main/java/com/example/comitserver/controller/StudyController.java
  src/main/java/com/example/comitserver/entity/StudyEntity.java
  src/main/java/com/example/comitserver/service/StudyService.java
Labels: fix

#30 feat: add identification before put and delete a study
  src/main/java/com/example/comitserver/controller/StudyController.java
  src/main/java/com/example/comitserver/service/StudyService.java
Labels: API, feature
