Repository skku-comit/comit-website-spring-server, pull requests merged in 2024-09, with the labels that each got.

#32 chore: adjust expire time of jwt tokens
  src/main/java/com/example/comitserver/jwt/JWTUtil.java
  src/main/java/com/example/comitserver/jwt/LoginFilter.java
  src/main/java/com/example/comitserver/service/ReissueService.java
Labels: chore

#40 feat: change response into response entity
  src/main/java/com/example/comitserver/controller/StudyController.java
Labels: API, feature

#42 feat(be): implement created study module
  src/main/java/com/example/comitserver/controller/UserController.java
  src/main/java/com/example/comitserver/entity/CreatedStudyEntity.java
  src/main/java/com/example/comitserver/repository/CreatedStudyRepository.java
  src/main/java/com/example/comitserver/service/StudyService.java
  src/main/java/com/example/comitserver/service/UserService.java
Labels: feature

#43 fix(be): prevent getting password
  src/main/java/com/example/comitserver/controller/JoinController.java
  src/main/java/com/example/comitserver/controller/UserAdminController.java
  src/main/java/com/example/comitserver/controller/UserController.java
  src/main/java/com/example/comitserver/dto/AdminUserResponseDTO.java
  src/main/java/com/example/comitserver/dto/StudyResponseDTO.java
  src/main/java/com/example/comitserver/dto/UserRequestDTO.java
  src/main/java/com/example/comitserver/dto/UserResponseDTO.java
  src/main/java/com/example/comitserver/entity/StudyEntity.java
  src/main/java/com/example/comitserver/service/UserService.java
  src/main/java/com/example/comitserver/utils/StringListConverter.java
Labels: feature

#47 feat: complete StudyAdminController
  src/main/java/com/example/comitserver/controller/StudyAdminController.java
  src/main/java/com/example/comitserver/controller/StudyController.java
Labels: API, feature

#48 feat(be): implement delete user for admin, edit spring security
  src/main/java/com/example/comitserver/config/SecurityConfig.java
  src/main/java/com/example/comitserver/controller/UserAdminController.java
  src/main/java/com/example/comitserver/service/UserAdminService.java
Labels: feature

#49 chore: changed function name
  src/main/java/com/example/comitserver/jwt/CustomLogoutFilter.java
  src/main/java/com/example/comitserver/jwt/JWTFilter.java
  src/main/java/com/example/comitserver/jwt/LoginFilter.java
  src/main/java/com/example/comitserver/utils/CustomAccessDeniedHandler.java
  src/main/java/com/example/comitserver/utils/ResponseUtil.java
Labels: chore

#51 add some methods of CreatedStudyRepository used by delete requests
  src/main/java/com/example/comitserver/repository/CreatedStudyRepository.java
  src/main/java/com/example/comitserver/service/StudyService.java
  src/main/java/com/example/comitserver/service/UserService.java
Labels: chore, fix

#54 fix isStaff error & refactor admin deleteUserbyId
  src/main/java/com/example/comitserver/controller/UserAdminController.java
  src/main/java/com/example/comitserver/controller/UserController.java
  src/main/java/com/example/comitserver/service/UserService.java
  src/main/java/com/example/comitserver/utils/GlobalExceptionHandler.java
Labels: chore

#56 55 admin update position
  src/main/java/com/example/comitserver/controller/UserAdminController.java
  src/main/java/com/example/comitserver/controller/UserController.java
  src/main/java/com/example/comitserver/service/UserAdminService.java
Labels: feature
